/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.monster.vista;
import ec.edu.monster.componentes.Estilos;
import ec.edu.monster.controlador.ConversionUnidadesController;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import ec.edu.monster.modelo.ConversionUnidades;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author rodri
 */
public class WebServiciosSoap extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WebServiciosSoap.class.getName());
    private int xMouse;
    private int yMouse;
    private final Color btnNAV = new Color(245, 245, 250);
     String ruta= "src/ec/edu/monster/img/rulers.png";
     String rutaB= "src/ec/edu/monster/img/justice.png";
     String rutaT= "src/ec/edu/monster/img/thermometer.png";
    ConversionUnidadesController controller;

    /**
     * Creates new form WebServiciosSoap
     */
    public WebServiciosSoap() {
        initComponents();
        Estilos.aplicarEstiloInput(txtValor);
        Estilos.aplicarEstiloComboBox(comboText);
        String[] opciones = {"Centimetros a Metros", "Metros  a Centimetros", "Metros a Kilometros"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(opciones);
        comboText.setModel(modelo);
        txtInfoT.setText("Seleccionar Conversión (Tipo: Longitud):");
        ConversionUnidades cu= new ConversionUnidades();
        controller= new ConversionUnidadesController(this,cu);
         ImageIcon icon = new ImageIcon(ruta);
         Image imgEscalada = icon.getImage().getScaledInstance(
                imgRegla.getWidth(),
                imgRegla.getHeight(),
                Image.SCALE_SMOOTH
        );
         imgRegla.setIcon(new ImageIcon(imgEscalada));
         ImageIcon iconB = new ImageIcon(rutaB);
         Image imgEscaladaB = iconB.getImage().getScaledInstance(
                imgB.getWidth(),
                imgB.getHeight(),
                Image.SCALE_SMOOTH
        );
         imgB.setIcon(new ImageIcon(imgEscaladaB));
         
         ImageIcon iconT = new ImageIcon(rutaT);
         Image imgEscaladaT = iconT.getImage().getScaledInstance(
                imgB.getWidth(),
                imgB.getHeight(),
                Image.SCALE_SMOOTH
        );
         imgT.setIcon(new ImageIcon(imgEscaladaT));
    }
    
    public  double getValor(){
        return   Double.parseDouble(txtValor.getText());
    }

    public String getTipoConversion(){
        return comboText.getSelectedItem().toString();
    }
    
    public void setResultado(String valor){
        txtResultado.setText(valor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        btnLongitud = new javax.swing.JPanel();
        lgtext = new javax.swing.JLabel();
        imgRegla = new javax.swing.JLabel();
        btnMasa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imgB = new javax.swing.JLabel();
        btnTemperatura = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        imgT = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtInfoT = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboText = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Web Service de Conversiones (RESTFULL)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        X.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X.setText("Cerrar Sesión");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 703, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        btnLongitud.setBackground(new java.awt.Color(255, 255, 255));
        btnLongitud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lgtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lgtext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgtext.setText("Longitud");
        lgtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgtextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgtextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgtextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnLongitudLayout = new javax.swing.GroupLayout(btnLongitud);
        btnLongitud.setLayout(btnLongitudLayout);
        btnLongitudLayout.setHorizontalGroup(
            btnLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLongitudLayout.createSequentialGroup()
                .addComponent(imgRegla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgtext, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        btnLongitudLayout.setVerticalGroup(
            btnLongitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLongitudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgRegla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lgtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 210, 40));

        btnMasa.setBackground(new java.awt.Color(255, 255, 255));
        btnMasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masa");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMasaLayout = new javax.swing.GroupLayout(btnMasa);
        btnMasa.setLayout(btnMasaLayout);
        btnMasaLayout.setHorizontalGroup(
            btnMasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnMasaLayout.setVerticalGroup(
            btnMasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(imgB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnMasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        btnTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        btnTemperatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Temperatura");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTemperaturaLayout = new javax.swing.GroupLayout(btnTemperatura);
        btnTemperatura.setLayout(btnTemperaturaLayout);
        btnTemperaturaLayout.setHorizontalGroup(
            btnTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTemperaturaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(imgT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btnTemperaturaLayout.setVerticalGroup(
            btnTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTemperaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(imgT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 630, -1));

        txtInfoT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInfoT.setText("Seleccionar Conversion");
        jPanel1.add(txtInfoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 630, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Valor a Convertir:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        comboText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboText.setBorder(null);
        jPanel1.add(comboText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 630, 40));

        btnConvertir.setBackground(new java.awt.Color(0, 0, 0));
        btnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Convertir");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnConvertirLayout = new javax.swing.GroupLayout(btnConvertir);
        btnConvertir.setLayout(btnConvertirLayout);
        btnConvertirLayout.setHorizontalGroup(
            btnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        btnConvertirLayout.setVerticalGroup(
            btnConvertirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 630, 40));

        jPanel3.setBackground(new java.awt.Color(207, 239, 207));

        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 630, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
       int  x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse  = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    private void XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseEntered
        btnExit.setBackground(Color.red);
        X.setForeground(Color.white);
    }//GEN-LAST:event_XMouseEntered

    private void XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseExited
        btnExit.setBackground(Color.white);
        X.setForeground(Color.black);

    }//GEN-LAST:event_XMouseExited

    private void lgtextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgtextMouseEntered
        btnLongitud.setBackground(btnNAV);
    }//GEN-LAST:event_lgtextMouseEntered

    private void lgtextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgtextMouseExited
        btnLongitud.setBackground(Color.white);
    }//GEN-LAST:event_lgtextMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        btnMasa.setBackground(btnNAV);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        btnMasa.setBackground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        btnTemperatura.setBackground(btnNAV);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        btnTemperatura.setBackground(Color.white);
    }//GEN-LAST:event_jLabel4MouseExited

    private void lgtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgtextMouseClicked
        String[] opciones = {"Centimetros a Metros", "Metros  a Centimetros", "Metros a Kilometros"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(opciones);
        comboText.setModel(modelo);
         txtInfoT.setText("Seleccionar Conversión (Tipo: Longitud):");
    }//GEN-LAST:event_lgtextMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String[] opciones = {"Tonelada a Libra", "Kilogramo a Libra", "Gramo a Kilogramo"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(opciones);
        comboText.setModel(modelo);
        txtInfoT.setText("Seleccionar Conversión (Tipo: Masa):");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         String[] opciones = {"Celsius a Fahrenheit", "Fahrenheit a Celsius", "Celsius a Kelvin"};
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(opciones);
        comboText.setModel(modelo);
        txtInfoT.setText("Seleccionar Conversión (Tipo: Temperatura):");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        controller.conversion();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WebServiciosSoap().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JPanel btnConvertir;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnLongitud;
    private javax.swing.JPanel btnMasa;
    private javax.swing.JPanel btnTemperatura;
    private javax.swing.JComboBox<String> comboText;
    private javax.swing.JLabel imgB;
    private javax.swing.JLabel imgRegla;
    private javax.swing.JLabel imgT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lgtext;
    private javax.swing.JLabel txtInfoT;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
