/* SQLINES DEMO *** atabase [BANQUITO]    Script Date: 25/01/2025 12:02:48 ******/
CREATE DATABASE IF NOT EXISTS BANQUITO;
USE BANQUITO;

CREATE TABLE `ELECTRODOMESTICO`(
	`Id` int AUTO_INCREMENT NOT NULL,
	`Nombre` nvarchar(100) NOT NULL,
	`Precio` decimal(18, 2) NOT NULL,
	`FotoUrl` Longtext NULL,
PRIMARY KEY 
(
	`Id` ASC
) 
) ;
 
CREATE TABLE `CLIENTE`(
	`COD_CLIENTE` char(7) NOT NULL,
	`CEDULA` nvarchar(10) NOT NULL,
	`NOMBRE` nvarchar(50) NOT NULL,
	`GENERO` char(1) NOT NULL,
	`FECHA_NACIMIENTO` date NOT NULL,
PRIMARY KEY 
(
	`COD_CLIENTE` ASC
) 
);

CREATE TABLE `CREDITO`(
	`COD_CREDITO` int AUTO_INCREMENT NOT NULL,
	`COD_CLIENTE` char(7) NOT NULL,
	`NUM_CUENTA` nvarchar(8) NOT NULL,
	`MONTO` decimal(10, 2) NOT NULL,
	`TASA_INTERES` decimal(5, 2) NOT NULL DEFAULT 16.5,
	`PLAZO_MESES` int NOT NULL,
	`FECHA_INICIO` date NOT NULL,
	`ESTADO` nvarchar(10) NOT NULL,
PRIMARY KEY 
(
	`COD_CREDITO` ASC
) 
);
CREATE TABLE `CUENTA`(
	`COD_CLIENTE` char(7) NOT NULL,
	`NUM_CUENTA` nvarchar(8) NOT NULL,
	`SALDO` decimal(10, 2) NOT NULL,
PRIMARY KEY 
(
	`COD_CLIENTE` ASC,
	`NUM_CUENTA` ASC
) 
);
 
CREATE TABLE `MOVIMIENTO`(
	`COD_CLIENTE` char(7) NOT NULL,
	`NUM_CUENTA` nvarchar(8) NOT NULL,
	`COD_MOVIMIENTO` int NOT NULL,
	`TIPO` nvarchar(10) NOT NULL,
	`VALOR` decimal(10, 2) NOT NULL,
	`FECHA` date NOT NULL,
 CONSTRAINT `PK_MOVIMIENTO` PRIMARY KEY 
(
	`NUM_CUENTA` ASC,
	`COD_MOVIMIENTO` ASC
) 
);
ALTER TABLE `CREDITO` ADD  CONSTRAINT `FK_CREDITO_CUENTA` FOREIGN KEY(`COD_CLIENTE`, `NUM_CUENTA`)
REFERENCES `CUENTA` (`COD_CLIENTE`, `NUM_CUENTA`)
ON DELETE CASCADE;
 
 
ALTER TABLE `CUENTA` ADD  CONSTRAINT `FK_CUENTA_CLIENTE` FOREIGN KEY(`COD_CLIENTE`)
REFERENCES `CLIENTE` (`COD_CLIENTE`)
ON DELETE CASCADE;
 
 
ALTER TABLE `MOVIMIENTO` ADD  CONSTRAINT `FK_MOVIMIENTO_CUENTA` FOREIGN KEY(`COD_CLIENTE`, `NUM_CUENTA`)
REFERENCES `CUENTA` (`COD_CLIENTE`, `NUM_CUENTA`);
 
 
ALTER TABLE `MOVIMIENTO` ADD CHECK  ((`VALOR`>=(0)));
 