//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_EUREKA_CLICON.EurekaService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EurekaService.EurekaServiceDBSoap")]
    public interface EurekaServiceDBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovimientoCuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMovimientoCuenta(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovimientoCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMovimientoCuentaAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDeposito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegistrarDeposito(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrarDepositoAsync(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRetiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegistrarRetiro(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRetiro", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrarRetiroAsync(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTransferencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegistrarTransferencia(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTransferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrarTransferenciaAsync(string cuenta, double importe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidarUsuario(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usuario, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EurekaServiceDBSoapChannel : WS_EUREKA_CLICON.EurekaService.EurekaServiceDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EurekaServiceDBSoapClient : System.ServiceModel.ClientBase<WS_EUREKA_CLICON.EurekaService.EurekaServiceDBSoap>, WS_EUREKA_CLICON.EurekaService.EurekaServiceDBSoap {
        
        public EurekaServiceDBSoapClient() {
        }
        
        public EurekaServiceDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EurekaServiceDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EurekaServiceDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EurekaServiceDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetMovimientoCuenta(string cuenta) {
            return base.Channel.GetMovimientoCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMovimientoCuentaAsync(string cuenta) {
            return base.Channel.GetMovimientoCuentaAsync(cuenta);
        }
        
        public bool RegistrarDeposito(string cuenta, double importe) {
            return base.Channel.RegistrarDeposito(cuenta, importe);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarDepositoAsync(string cuenta, double importe) {
            return base.Channel.RegistrarDepositoAsync(cuenta, importe);
        }
        
        public bool RegistrarRetiro(string cuenta, double importe) {
            return base.Channel.RegistrarRetiro(cuenta, importe);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarRetiroAsync(string cuenta, double importe) {
            return base.Channel.RegistrarRetiroAsync(cuenta, importe);
        }
        
        public bool RegistrarTransferencia(string cuenta, double importe) {
            return base.Channel.RegistrarTransferencia(cuenta, importe);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarTransferenciaAsync(string cuenta, double importe) {
            return base.Channel.RegistrarTransferenciaAsync(cuenta, importe);
        }
        
        public bool ValidarUsuario(string usuario, string password) {
            return base.Channel.ValidarUsuario(usuario, password);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usuario, string password) {
            return base.Channel.ValidarUsuarioAsync(usuario, password);
        }
    }
}
